### ISSUE TITLE
getLicense from manifest

### ISSUE THREAD

**Issue by jFaiad** [videojs/videojs-contrib-eme#106]
Hi! 
I get the license URL in the manifest, and simply using getLicense is not doing the trick. 

Is there an additional step I'm missing? Should I query the manifest myself or is there a function that does this for me?

Thank you

**Comment by gkatsev** [comment]
If you're using `getLicense` it means you are in charge of making the license request yourself and munging the data as appropriate before returning it to contrib-eme. You can also instead just give the url directly and have contrib-eme download it for you. How to provide it depends on the CDM you're using but it's outlined in the README.
