### ISSUE TITLE
fairplay stream not working

### ISSUE THREAD

**Issue by amit100075** [videojs/videojs-contrib-eme#127]
I am using  below URLs to play DRM, but playback is not working

https://content.uplynk.com/8d8708d41dba4de9b3b47d279e0d34da.m3u8?rmt=fps&drm_policy_name=TEST001

https://x-drm.uplynk.com/fairplay/public_key/30c99d5c0fb743218071b427384f4647.cer

please note I don't have licence URL, is there any way I can play this content or extract licence

**Comment by gkatsev** [comment]
If you do not have the license URL it is not possible to get the content to play back.
