### ISSUE TITLE
other drm example incorrect

### ISSUE THREAD

**Issue by bigt11** [videojs/videojs-contrib-eme#16]
Looks like you have the videoContentType and audioContentType data swapped for your other drm example.  Below is is fixed.  same applies to the source options example.  Having them incorrectly swapped causes code to error - fail.  Ironically I was using this for vp9 and vorbis and did not notice it right away.
```
{
  keySystems: {
    "org.w3.clearkey": {
      videoContentType: 'video/webm; codecs="vp9"',
      audioContentType: 'audio/webm; codecs="vorbis"',
      getCertificate: function(emeOptions, callback) {
        // request certificate
        // if err, callback(err)
        // if success, callback(null, certificate)
      },
      getLicense: function(emeOptions, keyMessage, callback) {
        // request license
        // if err, callback(err)
        // if success, callback(null, license)
      }
    }
  }
}
```

**Comment by gesinger** [comment]
Thanks @bigt11 ! Created PR https://github.com/videojs/videojs-contrib-eme/pull/18 to fix it.

**Comment by gesinger** [comment]
Merged the PR. Thanks again!
