### ISSUE TITLE
registerPlugin and webpack issue. EME pluging not registered.

### ISSUE THREAD

**Issue by qchroman** [videojs/videojs-contrib-eme#35]
Hello,

My test is very simple. I have a project in which I import the video.js, the videojs-contrib-hls and the videojs-contrib-eme to try and playback HLS + FP. But, for some reason, the videojs object doesn't have the eme plugin registered.

```
require('!style-loader!css-loader!video.js/dist/video-js.css');

import videojs from 'video.js'
import videojsContribHls from 'videojs-contrib-hls'
import videojsContribEme from 'videojs-contrib-eme'

const TestPlayer = function(id) {
  return videojs(id);
};

export default TestPlayer;
```

index.html
```
...
var player = new TestPlayer('my-player');
console.log(player.eme) // undefined
...
```

It only gets registered if I do this:

```
require('!style-loader!css-loader!video.js/dist/video-js.css');

import videojs from 'video.js'
import videojsContribHls from 'videojs-contrib-hls'
import videojsContribEme from 'videojs-contrib-eme'

const TestPlayer = function(id) {
  videojs.registerPlugin('eme', videojsContribEme);
  return videojs(id);
};

export default TestPlayer;
```

Note the call to registerPlugin in my TestPlayer constructor. Do you know why this may be happening?

Thank you in advance.

BR

**Comment by qchroman** [comment]
Furthermore, if you then set keySystems object inside player.src, it gets ignored. It only works when you pass options directly into player.eme. I thought that if the plugin is registered it should have noticed keySystems inside the src. I'm sure i'm doing something wrong, but I don't see what.

Any help is greatly appreciated.

Thank you.

**Comment by gesinger** [comment]
Hey @qchroman , thanks for posting all of the details. We've recently documented the initialization process for plugins (based on Video.js' standard initialization process) in the README https://github.com/videojs/videojs-contrib-eme#initialization . This is expected behavior for plugins.

**Comment by deepubohra** [comment]
I am following the initialization process for plugins (based on Video.js' standard initialization process) for https://github.com/videojs/videojs-contrib-eme#initialization but still getting error as below:
player.eme() is not a function where as player is instance of videojs
