### ISSUE TITLE
Help with slow parsing

### ISSUE THREAD

**Issue by Sivitas** [videojs/videojs-contrib-eme#36]
We've got widevine DRM setup with a dash playlist, and it's working properly.
On normal computers/laptops and the like, everything is working smoothly and quickly.
However we're seeing very slow parse times on a partner TV app.
Any advice on what we can do to identify the specific part that is causing the slowdown?

The video can be seen here:
https://videos.broadwayhd.com/watch/channel/featured/movie/16-kxdmUzZDE6lMnkqFS1tqUersmvBi5zVB-zxc-gabr1

The slowness from the logs on the tv:
![image](https://user-images.githubusercontent.com/4080198/37222311-70033f28-2381-11e8-8da4-8d3eadc4c79b.png)

The TV is running Opera v36, still waiting to hear back about the OS.

**Comment by gesinger** [comment]
Hey @Sivitas , it looks like you may be using dash.js (probably via videojs-contrib-dash) for this. Are you configuring EME through videojs-contrib-eme, or just using videojs-contrib-dash?

It also looks like those logs are coming from dash.js, where the parsing happens.

**Comment by Sivitas** [comment]
Hm, I didn't even realize the dash lib supported DRM directly. Looking at our code it seems we are using the videojs-contrib-dash `keySystemOptions` structure for widevine and this lib's `keySystems` structure for fairplay. 

Is there an implementation difference between the two?
I made the change to using `keySystems` on staging to test but there's an issue.

On my computer, the initial parse works but fails a little bit later
![image](https://user-images.githubusercontent.com/4080198/37225257-e50f2cba-238a-11e8-9f6c-797485400bce.png)

Staging link:
https://videostest.broadwayhd.com/watch/channel/featured/movie/16-thc2ZpYzE62t2lKQtCSK8XHW0u89g5F6-present-laughter

**Comment by gesinger** [comment]
There're some implementation differences. Feel free to use both as you were (contrib-dash/dash.js' keySystemOptions for most and contrib-eme for FairPlay).

In terms of the slow parsing, it looks like that may be for parsing the DASH manifest: https://github.com/Dash-Industry-Forum/dash.js/blob/d1afb0ecc31ba418243092b7bf06f5ee01c5cc3e/src/dash/parser/DashParser.js#L113 , which might not have to do with the DRM protection itself (unless it is having some trouble/slowness parsing the manifest data from within the manifest, but judging by the fact that both portions of the parser are slow, it might have more to do with the device's limitations).

**Comment by Sivitas** [comment]
That's what I was thinking as well, but wanted to check here just in case I missed something. Thanks for the help, going to close and let them know
