### ISSUE TITLE
custom request body for PlayReady DRM service using videojs-contrib-eme

### ISSUE THREAD

**Issue by subhranshudas** [videojs/videojs-contrib-eme#38]
Hi,
Is there any way to customize the request body & request headers we send using both player options and source for the DRM service, specifically PlayReady?
Thanks.

**Comment by gesinger** [comment]
Hey @subhranshudas , yes, it is possible to have completely custom requests by implementing the methods shown in https://github.com/videojs/videojs-contrib-eme#other-drm-systems . Please let us know if you have any more questions. Thank you.

**Comment by subhranshudas** [comment]
@gesinger Hi thanks for the reply, actually i had gone through [https://github.com/videojs/videojs-contrib-eme#playready-for-ie11-windows-81](url)
But i could not understand where to pass the custom request body and request headers in 
`  keySystems: {
    "com.microsoft.playready": "<your url here>"
  }
  // or
  keySystems: {
    "com.microsoft.playready": {
      "url": "<your url here>"
    }
  }`

If you can illustrate with a snippet. 

Thanks.
