### ISSUE TITLE
Dash eme playready with customdata configuration

### ISSUE THREAD

**Issue by silverrangerted** [videojs/videojs-contrib-eme#40]
Hi guys any equivalen sample with videojs-contrib-eme config with that sample ? 
I dont see any sample with custom data on playready sample !
var player = videojs('example-video');
player.ready(function() {
  player.src({
    src: 'http://203.162.70.105/__cl/default/__c/ch2/__op/playready/__f/index.mpd',
    type: 'application/dash+xml',
	keySystemOptions: [{
    name: 'com.microsoft.playready',
    options: {
      licenseUrl: 'http://194.248.68.212/cxplayready/rightsmanager.asmx',
      httpRequestHeaders: { 'Conax-Custom-Data': customData },
      clearkeys: ''
    }
  }]
  });

  player.play();
});

**Comment by gesinger** [comment]
Hey @silverrangerted , it looks like you may be configuring your options using another system's format. videojs-contrib-eme accepts `keysSystems` via https://github.com/videojs/videojs-contrib-eme#other-drm-systems . What are you using to play back the DASH video?

**Comment by silverrangerted** [comment]
Hi @gesinger thank you very much for reply , my question simply mean : 
Any simple configuration on videojs-contrib-eme so i can add customdata (playready drm system)?
