### ISSUE TITLE
Unable to play dash with drm

### ISSUE THREAD

**Issue by amtins** [videojs/videojs-contrib-eme#50]
Hi,

I built a small [project](https://github.com/amtins/videojs-dash-drm-fail) to demonstrate my incapacity to play a dash video with drm. Could you have a look please ? :kissing_closed_eyes::+1:

**Comment by forbesjo** [comment]
You'll need to initialize the contrib-eme plugin by calling `player.eme()`. We'll update the getting started section of the READMEE so this is clear.
