### ISSUE TITLE
config options

### ISSUE THREAD

**Issue by slash197** [videojs/videojs-contrib-eme#56]
I cannot find a specific way to implement custom headers with widevine, using the config below does not work. Any help is appreciated.

		_source = {
			src: 'https://02live00.akamaized.net/CLOUDTV_RTL8HD/Manifest.mpd',
			type: 'application/dash+xml',
			keySystemOptions: [{
				name: 'com.widevine.alpha',
				options: {
					licenseUrl: 'https://wv-keyos.licensekeyserver.com',
					httpRequestHeaders: {customdata: 'PEtleU9TQXV0aGVudGljYXRpb25YTUw+CjxEYXRhPg..........'}
				}
			}]
		};

**Comment by squarebracket** [comment]
It looks like you're using the configs from videojs/videojs-contrib-dash. They are not directly transferable. There is also no "simple field" for providing your own HTTP headers; you'll have to implement your own `getLicense` function, as shown [here](https://github.com/videojs/videojs-contrib-eme#source-options).

You'll want to do something like:
```javascript
let source = {
  src: mySrc,
  type: 'application/dash+xml',
  keySystems = {
    'com.widevine.alpha': {
      getLicense: function(emeOptions, keyMessage, callback) {
        let message = new Uint8Array(keyMessage);
        videojs.xhr({
          uri: widevineUrl,
          method: 'POST',
          responseType: 'arraybuffer',
          body: message,
          headers: myHeaders
        }, (err, response, responseBody) => {
          if (err) {
            callback(err);
            return;
          }
          callback(null, responseBody);
        });
      }
    }
  }
};
```

**Comment by slash197** [comment]
Thank you for the details, appreciate it.
