### ISSUE TITLE
DASH + Widevine: no error, no video

### ISSUE THREAD

**Issue by Kogoruhn** [videojs/videojs-contrib-eme#63]
Hi! I use contrib-eme according to manual:

```
    player.eme();
    player.src({
      "src": "https://server/file.mpd",
      "type": "application/dash+xml",
      "keySystems": {
        "com.widevine.alpha": "https://server/proxy"
      }
    });
```

Got just this warn (x3 times): 
> It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior.

I use local server with https, navigator.requestMediaKeySystemAccess is present.
    "video.js": "^7.2.3",
    "videojs-contrib-eme": "^3.4.1"

Network shows x2 post requests to proxy w/o errors.

**Comment by Kogoruhn** [comment]
As I understand, this error is due to `videojs-http-streaming`, which was included in 7.* videojs versions.

**Comment by tidemann** [comment]
did you manage to solve this problem?

**Comment by Kogoruhn** [comment]
@tidemann [This](https://github.com/videojs/http-streaming/issues/260#issuecomment-433939804) works for me
