### ISSUE TITLE
Issue when playing HLS with playready

### ISSUE THREAD

**Issue by asadmalik3** [videojs/videojs-contrib-eme#65]
I am trying to play encrypted stream in HLS format. Issue is that fragments are successfully downloaded but acquire license call is never sent to the server. Is there anything i need to check?

**Comment by forbesjo** [comment]
Would you be able to provide a link to your stream or test page so we can investigate your issue?

**Comment by misteroneill** [comment]
We are not aware of any case where HLS works with PlayReady. All implementations of PlayReady we've seen use DASH.
