### ISSUE TITLE
Playback HLS format with FairPlay encryption using Azure Media Services

### ISSUE THREAD

**Issue by tabas** [videojs/videojs-contrib-eme#93]
Hi,

I try to integrate Azure Media Servies and DRM with Video.js player. To playback of encrypted content, I also use videojs-contrib-eme plugin for Video.js.
I succeed with MPEG DASH and PlayReady/Widevine encryptions and I have problems with HLS format and Fair encryption. My player source object looks as in the picture below:

![source](https://user-images.githubusercontent.com/5165482/63975455-c2f25c80-cab7-11e9-9e70-555912857006.png)

I'm getting the next error:

![Annotation 2019-08-29 234249](https://user-images.githubusercontent.com/5165482/63975484-d30a3c00-cab7-11e9-99e5-dacc6bcc3a4e.png)

I look like Video.js works bad with my license URL which starts with "skd://" and it fails due to cross-origin policy.

Have I missed something in my implementation?
Thanks

**Comment by MTonomy-Nchinda-Nchinda** [comment]
I have a similar setup with ezdrm. Change "skd" to "https" in the configuration you've posted.

**Comment by gkatsev** [comment]
Thanks for answering @MTonomy-Nchinda-Nchinda.
