### ISSUE TITLE
Error on PlayReady: "plugin "eme" does not exist"

### ISSUE THREAD

**Issue by nskhara** [videojs/videojs-contrib-eme#94]
Hello.

When trying PlayReady on Windows 10 Edge/IE11, an error appears in the console.
> plugin "eme" does not exist

I can't figure out what the problem is though do you have any idea?

Below is the html I am using (in text file).
[index.txt](https://github.com/videojs/videojs-contrib-eme/files/3572410/index.txt)

Currently, this is as far as I know.

1. License request will be thrown and succeeds but it will not start playback.
1. When I delete "data-setup='{"plugins": {"eme": {}}}'" on the video tag, the error disappears, though it will not start playback.(License request will succeed)

NOTE:
The code works fine when executing on Chrome+Widevine.

**Comment by MTonomy-Nchinda-Nchinda** [comment]
Make sure to import the plugin first. Either import it into your html file using a src tag. Or add 
`import videojs-contrib-eme` to your javascript.

**Comment by gkatsev** [comment]
Basically, remove the data-setup attribute and instead call eme() manually, or pass the `{plugins: {eme: {}}}` options to videojs().
